# services/reserved_words.py

RESERVED_WORDS = {

    "AFFICHER": "AFFICHER",
    "STATISTIQUES": "STATISTIQUES",
    "ERREURS": "ERREURS",

    "LANCER": "LANCER",
    "ENQUETE": "ENQUETE",
    "CYBERSECURITE": "CYBERSECURITE",
    "CAMPAGNE": "CAMPAGNE",
    "ECOLE": "ECOLE",

    "CHERCHER": "CHERCHER",
    "ENFANTS": "ENFANTS",
    "KINSHASA": "KINSHASA",
    "ADOLESCENTS": "ADOLESCENTS",
    "INTERESSES": "INTERESSES",
    "PAR": "PAR",
    "PYTHON": "PYTHON",

    "AJOUTER": "AJOUTER",
    "QUESTION": "QUESTION",

    "MODIFIER": "MODIFIER",
    "SUPPRIMER": "SUPPRIMER",

    "EXPORTER": "EXPORTER",
    "RAPPORT": "RAPPORT",

    "RECOMMENCER": "RECOMMENCER",
    "SESSION": "SESSION",

    "QUITTER": "QUITTER"
}